#ifndef __CONTROL_IDS_H__
#define __CONTROL_IDS_H__

#define IDC_LEFT_SUB_WINDOW 201
#define IDC_RIGHT_SUB_WINDOW 202
#define IDC_CREATE_PANEL_SELECTOR 203
#define IDC_NODE_NAME_TEXTFIELD 204

#define IDC_NEW_MODEL_NDOE_BTN 301
#define IDC_ALL_MESH_COMBO 302
#define IDC_CREATE_STATIC_CHECK_BOX 303
#define	IDC_NODES_LIST 304

#define IDC_POS_TEXTFIELD 400
#define IDC_ROT_TEXTFIELD 403
#define IDC_SCALE_TEXTFIELD 406
#define IDC_UPDATE_TRANSFORM_BTN 410
#define IDC_CANCEL_TRANSFORM_BTN 411
#define IDC_NODE_INFO_STATIC_CHECKBOX 412
#define IDC_NODE_INFO_PHYSICS_CHECKBOX 413
#define IDC_NODE_INFO_SHADOW_CHECKBOX 414

#define IDC_NODE_INFO_LABEL 450

#endif

