#ifndef __CONTROL_IDS_H__
#define __CONTROL_IDS_H__

#define IDC_LEFT_SUB_WINDOW 201
#define IDC_RIGHT_SUB_WINDOW 202
#define IDC_CREATE_PANEL_SELECTOR 203
#define IDC_NODE_NAME_TEXTFIELD 204

#define IDC_NEW_MODEL_NDOE_BTN 301
#define IDC_ALL_MESH_COMBO 302
#define IDC_CREATE_STATIC_CHECK_BOX 303
#define	IDC_NODES_LIST 304
#define IDC_CREATE_MULTIPLE_CHECKBOX 305
#define IDC_CREATE_MULTIPLE_NUM_TEXTFILED 306
#define IDC_DELETE_MESH_NODE_BTN 307

#define IDC_POS_TEXTFIELD 400
#define IDC_ROT_TEXTFIELD 403
#define IDC_SCALE_TEXTFIELD 406
#define IDC_UPDATE_TRANSFORM_BTN 410
#define IDC_CANCEL_TRANSFORM_BTN 411
#define IDC_NODE_INFO_STATIC_CHECKBOX 412
#define IDC_NODE_INFO_PHYSICS_CHECKBOX 413
#define IDC_NODE_INFO_SHADOW_CHECKBOX 414
#define IDC_NODE_INFO_LABEL 450


#define IDC_INSTANCE_NAME_TEXTFILED 501
#define IDC_INSTANCE_CREATE_BTN 502
#define IDC_INSTANCE_LISTBOX 503
#define IDC_INSTANCE_DELETE_BTN 504


#define IDC_CREATE_LIGHT_BTN 601
#define IDC_DELETE_LIGHT_BTN 602
#define IDC_LIGHT_NODE_LISTBOX 603
#define IDC_LIGHT_NAME_TEXTFIELD 604


#define IDC_LIGHT_INFO_LABEL 700
#define IDC_LIGHT_POS_TEXTFIELD 720
#define IDC_LIGHT_DIFF_TEXTFIELD 723
#define IDC_LIGHT_SPEC_TEXTFIELD 726
#define IDC_LIGHT_ATTEN_TEXTFIELD 729
#define IDC_LIGHT_RANGE_TEXTFIELD 733
#define IDC_LIGHT_UPDATE_BTN 734
#define IDC_LIGHT_CANCEL_BTN 735
#define IDC_LIGHT_STATIC_CHECKBOX 736

#define IDC_GLOBAL_LABEL 800
#define IDC_SAVE_SCENE_BTN 820
#define IDC_SCENE_AMBIENT_TEXTFIELD 821
#define IDC_SCENE_DIFFUSE_TEXTFIELD 822
#define IDC_SCENE_SPECULAR_TEXTFIELD 823
#define IDC_SCENE_UPDATE_BTN 824
#define IDC_DEFER_SHADING_CHECKBOX 825

#endif

