#ifndef __CONTROL_IDS_H__
#define __CONTROL_IDS_H__


#define IDC_MESH_COMBO		201
#define IDC_MESH_AABB_CENTER_LABEL 202
#define IDC_MESH_AABB_EXTEND_LABEL 203


#define IDC_BOUNDING_CATEGORY_COMBO 301
#define IDC_CREATE_BOUNDING_BTN 302
#define IDC_DELETE_BOUNDING_BTN 303
#define IDC_BOUNDINGS_LISTBOX 304
#define IDC_SAVE_BUTTON 305

#define IDC_BOUNDING_CENTER_TEXTFIELD 306
#define IDC_BOUNDING_UPDATE_BUTTON 310
#define IDC_BOUNDING_ROTATION_TEXTFIELD 313
#define IDC_BOUNDING_MASS_TEXTFIELD 317
#define IDC_BOUNDING_FRICTION_TEXTFIELD 318
#define IDC_CREATE_BOUNDING_LABELS 350

#define IDC_BOX_SIZE_TEXTFIELD 401
#define IDC_BOX_LABELS 450


#endif